---
- name: "Create Dir"
  file:
    path: ~/backend-app
    state: directory

- name: "Unarchive"
  unarchive:
    src: /home/artifact.tar.gz
    dest: ~/backend-app/

#- name: Copy backend files
#  become: true
#  copy:
#      src: /home/artifact.tar.gz
#      dest: /home/ubuntu/artifact.tar.gz

- name: "Install dep"
  shell: |
      cd ~/backend-app
      npm install typescript -g
      npm i

- name: "Exec PM2"
  shell: |
      cd ~/backend-app/dist
      pm2 stop default
      pm2 start main.js

- name: "PM2 as a service"
  shell: |
      sudo su -c "env PATH:$PATH:/usr/local/bin pm2 startup systemd -u ubuntu --hp /home/ubuntu"
      pm2 save