---
- name: "Create Directory"
  file:
    path: ~/backend-app
    state: directory

- name: "Unarchive Artifact"
  unarchive:
    src: /home/artifact.tar.gz
    dest: ~/backend-app/

- name: "Install Deployment 1"
  command: |
    apt update
    apt install curl -y
    apt install ansible -y
    apt install aws-cli
    apt install tar gzip nodejs npm

- name: "Hi test"
  command: |
    cd ~/backend-app
    npm install typescript
    npm i

- name: "Exec PM2"
  command: |
    sudo npm install pm2
    cd ~/backend-app/dist
    pm2 stop default
    pm2 start main.js

- name: "PM2 as a service"
  shell: |
    sudo su -c "env PATH:$PATH:/usr/local/bin pm2 startup systemd -u ubuntu --hp /home/ubuntu"
    pm2 save
