---
- name: "Create Directory"
  file:
    path: ~/backend-app
    state: directory

- name: "Unarchive Artifact"
  unarchive:
    src: /home/artifact.tar.gz
    dest: ~/backend-app/

- name: "Install Dependencies"
  shell: |
      cd ~/backend-app
      npm install typescript -g
      npm i

- name: "Start the Application"
  shell: |
      cd ~/backend-app/dist
      pm2 stop default
      pm2 start main.js

- name: "Run PM2 as a service"
  shell: |
      sudo su -c "env PATH:$PATH:/usr/local/bin pm2 startup systemd -u ubuntu --hp /home/ubuntu"
      pm2 save